version: '3'

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.21.0rc4
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - MEILI_MASTER_KEY
      - MEILI_ENV=production
    volumes: 
      - ./data.ms:/data.ms
    ports:
      - 7700:7700
    restart: unless-stopped