version: '3'

services:

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.12.0
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    ports:
      - 7700:7700
    restart: unless-stopped
